import { Country } from './types';

export const INITIAL_COUNTRIES: Omit<Country, 'wins' | 'isChampion'>[] = [
  { id: 'us', code: 'us', name: 'USA', color: '#3C3B6E' },
  { id: 'gb', code: 'gb', name: 'UK', color: '#C8102E' },
  { id: 'fr', code: 'fr', name: 'France', color: '#0055A4' },
  { id: 'de', code: 'de', name: 'Germany', color: '#DD0000' },
  { id: 'jp', code: 'jp', name: 'Japan', color: '#BC002D' },
  { id: 'br', code: 'br', name: 'Brazil', color: '#009C3B' },
  { id: 'ca', code: 'ca', name: 'Canada', color: '#FF0000' },
  { id: 'au', code: 'au', name: 'Australia', color: '#00008B' },
  { id: 'it', code: 'it', name: 'Italy', color: '#008C45' },
  { id: 'es', code: 'es', name: 'Spain', color: '#AA151B' },
  { id: 'in', code: 'in', name: 'India', color: '#FF9933' },
  { id: 'cn', code: 'cn', name: 'China', color: '#EE1C25' },
  { id: 'mx', code: 'mx', name: 'Mexico', color: '#006847' },
  { id: 'kr', code: 'kr', name: 'South Korea', color: '#0047A0' },
  { id: 'ng', code: 'ng', name: 'Nigeria', color: '#008751' },
  { id: 'ar', code: 'ar', name: 'Argentina', color: '#75AADB' },
  { id: 'za', code: 'za', name: 'South Africa', color: '#007A4D' },
  { id: 'se', code: 'se', name: 'Sweden', color: '#006AA7' },
  { id: 'nl', code: 'nl', name: 'Netherlands', color: '#21468B' },
  { id: 'ch', code: 'ch', name: 'Switzerland', color: '#FF0000' },
  { id: 'tr', code: 'tr', name: 'Turkey', color: '#E30A17' },
  { id: 'pl', code: 'pl', name: 'Poland', color: '#DC143C' },
  { id: 'id', code: 'id', name: 'Indonesia', color: '#FF0000' },
  { id: 'sa', code: 'sa', name: 'Saudi Arabia', color: '#006C35' },
  { id: 'pt', code: 'pt', name: 'Portugal', color: '#006600' },
  { id: 'no', code: 'no', name: 'Norway', color: '#BA0C2F' },
  { id: 'eg', code: 'eg', name: 'Egypt', color: '#CE1126' },
  { id: 'th', code: 'th', name: 'Thailand', color: '#2D2A4A' },
  { id: 'vn', code: 'vn', name: 'Vietnam', color: '#DA251D' },
  { id: 'gr', code: 'gr', name: 'Greece', color: '#001489' },
  { id: 'fi', code: 'fi', name: 'Finland', color: '#003580' },
  { id: 'ph', code: 'ph', name: 'Philippines', color: '#0038A8' },
  { id: 'be', code: 'be', name: 'Belgium', color: '#000000' },
  { id: 'dk', code: 'dk', name: 'Denmark', color: '#C60C30' },
  { id: 'ie', code: 'ie', name: 'Ireland', color: '#169B62' },
  { id: 'at', code: 'at', name: 'Austria', color: '#ED2939' },
  { id: 'nz', code: 'nz', name: 'New Zealand', color: '#00247D' },
  { id: 'sg', code: 'sg', name: 'Singapore', color: '#ED2939' },
  { id: 'my', code: 'my', name: 'Malaysia', color: '#010066' },
  { id: 'ua', code: 'ua', name: 'Ukraine', color: '#0057B8' },
  { id: 'co', code: 'co', name: 'Colombia', color: '#FCD116' },
  { id: 'cl', code: 'cl', name: 'Chile', color: '#DA291C' },
  { id: 'pe', code: 'pe', name: 'Peru', color: '#D91023' },
  { id: 'pk', code: 'pk', name: 'Pakistan', color: '#115740' },
  { id: 'ma', code: 'ma', name: 'Morocco', color: '#C1272D' },
  { id: 'ke', code: 'ke', name: 'Kenya', color: '#000000' },
  { id: 'cz', code: 'cz', name: 'Czechia', color: '#11457E' },
  { id: 'hu', code: 'hu', name: 'Hungary', color: '#477050' },
  { id: 'hr', code: 'hr', name: 'Croatia', color: '#FF0000' },
  { id: 'uy', code: 'uy', name: 'Uruguay', color: '#0038A8' },
  { id: 'jm', code: 'jm', name: 'Jamaica', color: '#000000' },
  { id: 'bd', code: 'bd', name: 'Bangladesh', color: '#006A4E' },
  { id: 'ir', code: 'ir', name: 'Iran', color: '#239F40' },
  { id: 'il', code: 'il', name: 'Israel', color: '#0038B8' },
  { id: 'ro', code: 'ro', name: 'Romania', color: '#002B7F' },
  { id: 'rs', code: 'rs', name: 'Serbia', color: '#C6363C' },
  { id: 'qa', code: 'qa', name: 'Qatar', color: '#8D1B3D' },
  { id: 'ec', code: 'ec', name: 'Ecuador', color: '#FFDD00' },
  { id: 'sn', code: 'sn', name: 'Senegal', color: '#00853F' },
  { id: 'dz', code: 'dz', name: 'Algeria', color: '#006233' },
  { id: 've', code: 've', name: 'Venezuela', color: '#FFCC00' },
  { id: 'cu', code: 'cu', name: 'Cuba', color: '#002A8F' },
  { id: 'is', code: 'is', name: 'Iceland', color: '#02529C' },
  { id: 'gh', code: 'gh', name: 'Ghana', color: '#006B3F' },
  { id: 'cr', code: 'cr', name: 'Costa Rica', color: '#002B7F' },
  { id: 'sk', code: 'sk', name: 'Slovakia', color: '#0B4EA2' },
  { id: 'kz', code: 'kz', name: 'Kazakhstan', color: '#00AFCA' },
  { id: 'mn', code: 'mn', name: 'Mongolia', color: '#DA2032' },
  { id: 'bo', code: 'bo', name: 'Bolivia', color: '#007934' },
  { id: 'py', code: 'py', name: 'Paraguay', color: '#D52B1E' },
  { id: 'jo', code: 'jo', name: 'Jordan', color: '#CE1126' },
  { id: 'bg', code: 'bg', name: 'Bulgaria', color: '#00966E' },
  { id: 'et', code: 'et', name: 'Ethiopia', color: '#009A44' },
  { id: 'tw', code: 'tw', name: 'Taiwan', color: '#FE0000' },
  { id: 'pa', code: 'pa', name: 'Panama', color: '#DA121A' },
  { id: 'ee', code: 'ee', name: 'Estonia', color: '#0072CE' },
  { id: 'lk', code: 'lk', name: 'Sri Lanka', color: '#8D153A' },
  { id: 'al', code: 'al', name: 'Albania', color: '#E41E20' },
  { id: 'mk', code: 'mk', name: 'North Macedonia', color: '#D20000' },
  { id: 'ba', code: 'ba', name: 'Bosnia', color: '#002395' },
  { id: 'si', code: 'si', name: 'Slovenia', color: '#005CE6' },
  { id: 'lv', code: 'lv', name: 'Latvia', color: '#9E3039' },
  { id: 'lt', code: 'lt', name: 'Lithuania', color: '#FDB913' },
  { id: 'by', code: 'by', name: 'Belarus', color: '#D22730' },
  { id: 'md', code: 'md', name: 'Moldova', color: '#0046AE' },
  { id: 'am', code: 'am', name: 'Armenia', color: '#D90012' },
  { id: 'az', code: 'az', name: 'Azerbaijan', color: '#00B5E2' },
  { id: 'ge', code: 'ge', name: 'Georgia', color: '#FF0000' },
  { id: 'uz', code: 'uz', name: 'Uzbekistan', color: '#0099B5' },
  { id: 'np', code: 'np', name: 'Nepal', color: '#DC143C' },
  { id: 'kh', code: 'kh', name: 'Cambodia', color: '#032EA1' },
  { id: 'mm', code: 'mm', name: 'Myanmar', color: '#FECB00' },
  { id: 'lb', code: 'lb', name: 'Lebanon', color: '#ED1C24' },
  { id: 'kw', code: 'kw', name: 'Kuwait', color: '#007A3D' },
  { id: 'tn', code: 'tn', name: 'Tunisia', color: '#E70013' },
  { id: 'cm', code: 'cm', name: 'Cameroon', color: '#007A5E' },
  { id: 'do', code: 'do', name: 'Dominican Rep.', color: '#002D62' },
  { id: 'ae', code: 'ae', name: 'UAE', color: '#00732F' },
  { id: 'om', code: 'om', name: 'Oman', color: '#DB161B' },
  { id: 'bh', code: 'bh', name: 'Bahrain', color: '#CE1126' },
  { id: 'cy', code: 'cy', name: 'Cyprus', color: '#D57800' },
  { id: 'mt', code: 'mt', name: 'Malta', color: '#C8102E' },
  { id: 'lu', code: 'lu', name: 'Luxembourg', color: '#00A1DE' },
  { id: 'tz', code: 'tz', name: 'Tanzania', color: '#1EB53A' },
  { id: 'ug', code: 'ug', name: 'Uganda', color: '#000000' },
  { id: 'ci', code: 'ci', name: 'Ivory Coast', color: '#FF8200' },
  { id: 'mg', code: 'mg', name: 'Madagascar', color: '#FC3D32' },
  { id: 'zw', code: 'zw', name: 'Zimbabwe', color: '#006430' },
  { id: 'gt', code: 'gt', name: 'Guatemala', color: '#4997D0' },
  { id: 'hn', code: 'hn', name: 'Honduras', color: '#0073CF' },
  { id: 'sv', code: 'sv', name: 'El Salvador', color: '#0F47AF' },
  { id: 'ni', code: 'ni', name: 'Nicaragua', color: '#0067C6' },
  { id: 'tt', code: 'tt', name: 'Trinidad', color: '#CE1126' },
  { id: 'fj', code: 'fj', name: 'Fiji', color: '#68BFE5' },
  { id: 'pg', code: 'pg', name: 'Papua NG', color: '#CE1126' },
  { id: 'la', code: 'la', name: 'Laos', color: '#002868' },
  { id: 'me', code: 'me', name: 'Montenegro', color: '#C40308' }
];

export const GAME_CONFIG = {
  WINS_TO_CHAMPION: 4,
  MAX_CHAMPIONS_SHOWN: 4, // Stop after top 4
  ARENA_ROTATION_SPEED: 0.002, // Slower rotation (was 0.005)
  BALL_SIZE: 12,
  GAP_SIZE_DEGREES: 25, // Smaller gap (was 30) for harder elimination
};